# Generated by Django 2.1.7 on 2019-03-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0003_auto_20190326_1824'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='options_selection',
            unique_together={('question_id', 'option_id')},
        ),
    ]
