# Generated by Django 2.1.7 on 2019-03-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0004_auto_20190326_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options_selection',
            old_name='question_id',
            new_name='question',
        ),
        migrations.AlterUniqueTogether(
            name='options_selection',
            unique_together={('question', 'option_id')},
        ),
    ]
