# Generated by Django 2.1.7 on 2019-03-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0005_auto_20190326_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveys',
            old_name='question_id',
            new_name='question',
        ),
    ]
