# Generated by Django 2.1.7 on 2019-03-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0007_auto_20190327_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveys',
            name='survey_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
