# Generated by Django 2.1.7 on 2019-04-05 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0009_auto_20190329_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='option_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dappx.options_selection'),
        ),
    ]
