# Generated by Django 2.1.7 on 2019-04-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0012_date_answers_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveys',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
