# Generated by Django 2.1.7 on 2019-04-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0014_remove_surveys_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='answer_sel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
