# Generated by Django 2.1.7 on 2019-04-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0017_remove_surveys_answer_sel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveys',
            old_name='o_id',
            new_name='option',
        ),
    ]
