# Generated by Django 2.1.7 on 2019-04-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0018_auto_20190406_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveys',
            old_name='answer_date_id',
            new_name='date_answer',
        ),
    ]
